Logs refactoring
retailcrm/woocommerce-module pull request #344
Opened 2024-09-17 10:02 UTC by Chupocabra

Add log:
- action entrypoint, 
- action identifier, 
- action time. 

Change log format to json. More info logs. Always in debug mode

2024-09-17 18:33 UTC, gleemand requested changes
Общее замечание по логам, где просто выводятся id сущностей или сами сущности: непонятно, что в моменте с ними происходит, для чего вообще этот лог. Стоит добавить короткое описание типа "происходит действие с товаром <товар>", т.к. поддержке может быть сложно интерпретировать логи.

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +            WC_Retailcrm_Logger::info(__METHOD__, 'Updating WC_Order: ' . WC_Retailcrm_Logger::formatWCObject($wcOrder));
отдели от if

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +            WC_Retailcrm_Logger::info(__METHOD__, 'Creating WC_Order from CRM_Order: ' . json_encode($order));
отдели от if

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +                    WC_Retailcrm_Logger::error(
PSR-12 4.7

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
>                          continue;
перед return/continue/break я бы оставил пустую строку

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +                        WC_Retailcrm_Logger::error(__METHOD__, 'Product not found by ' . $this->bindField);
добавь инфы, что за продукт

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +                    WC_Retailcrm_Logger::error(__METHOD__, sprintf(
PSR-12 4.7

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +                        'Exception in file - ' . $exception->getFile() . ' on line ' . $exception->getLine()),
добавь этот текст сразу в формат стринг

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-history.php
> +                'Using this individual person data in order to set it into order,' .
нечитаемо. используй лучше sprintf

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +            WC_Retailcrm_Logger::info(__METHOD__, 'Start order creating ' . $orderId);
отдели от if

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                    __METHOD__, 'WC_Order: ' . WC_RETAILCRM_LOGGER::formatWCObject($wcOrder)
PSR-1 3

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                WC_Retailcrm_Logger::info(
PSR-12 4.7

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                'WC_Customer ID: %s email: %s WC_Order ID: %s', $wcCustomerId, $wcCustomerEmail, $wcOrder->get_id())
PSR-12 4.7

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                    __METHOD__, 'WC_Order: ' . WC_Retailcrm_Logger::formatWCObject($wcOrder)
PSR-12 4.7

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
>                  return;
перед return/continue/break пустую строку

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                    __METHOD__, 'WC_Order_Item_Product: ' . WC_RETAILCRM_LOGGER::formatWCObject($item)
- PSR-1 3
- PSR-12 4.7
- подними лог в начало цикла, т.к. при ошибке мы не узнаем об этом товаре

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-uploader.php
> +            WC_Retailcrm_Logger::info(__METHOD__, 'IDs: ' . implode(', ', $ids));
отдели от if

2024-09-17 18:33 UTC, gleemand commented on src/include/order/class-wc-retailcrm-order-address.php
> +            WC_Retailcrm_Logger::error(__METHOD__, 'Error: Order address is empty');
могут быть кейсы, когда мы не узнаем, в каком заказе ошибка?

2024-09-17 18:33 UTC, gleemand commented on src/include/class-wc-retailcrm-customers.php
> +                __METHOD__, 'WC_Customer: ' . WC_Retailcrm_Logger::formatWCObject($customer)
PSR-12 4.7

2024-09-18 08:50 UTC, uryvskiy-dima reviewed
Также необходимо сделать rebase и добавить bump версии модуля.

2024-09-18 11:01 UTC, Chupocabra commented on src/include/order/class-wc-retailcrm-order-address.php
> +            WC_Retailcrm_Logger::error(__METHOD__, 'Error: Order address is empty');
Вызывается только в WC_Retailcrm_Orders::processOrder, перед которым есть логи заказа

2024-09-19 12:12 UTC, gleemand requested changes

2024-09-19 12:12 UTC, gleemand commented on src/include/api/class-wc-retailcrm-proxy.php
> +                        WC_Retailcrm_Logger::TYPE['res']
raw response в контекст

2024-09-19 12:12 UTC, gleemand commented on src/include/api/class-wc-retailcrm-proxy.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/api/class-wc-retailcrm-proxy.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/api/class-wc-retailcrm-proxy.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-cart.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-cart.php
> +                    WC_Retailcrm_Logger::TYPE['exc'])
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-loyalty.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-loyalty.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-loyalty.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-loyalty.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/class-wc-retailcrm-orders.php
> +                    WC_Retailcrm_Logger::TYPE['exc']
трейс в контекс

2024-09-19 12:12 UTC, gleemand commented on src/include/components/class-wc-retailcrm-logger.php
> +        private static function log(string $method, string $message, $type = null, array $context = [], $level = 'info')
Необязательные аргументы лучше расположить по частоте использования. При вызове методов info, error, log часто третий параметр указываешь явно null. Контекст чаше передается, чем тип, поэтому лучше его поставить перед типом. Меньше null`ов нужно будет писать

2024-09-20 09:24 UTC, gleemand commented
метод writeBaseLogs не везде заменен на новый

2024-09-20 12:22 UTC, gleemand approved these changes

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::info(__METHOD__, 'Creation is not from admin panel, skip');
Этот хук именно для создания через админ панель

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Стоит задуматься над вынесением записи исключений в логи в статический метод класса WC_Retailcrm_Logger у тебя этот код дублируется по всему модулю

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-base.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-cart.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-cart.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-history.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-history.php
> +                            WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-history.php
> +                            WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-history.php
> +                    WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-loyalty.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-loyalty.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-loyalty.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-loyalty.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-orders.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-orders.php
> +                WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-upload-discount-price.php
> +                    WC_Retailcrm_Logger::error(
Дублирование кода

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/components/class-wc-retailcrm-logger.php
> +            if (empty(static::$logIdentifier)) {
Не используй empty, logIdentifier - строка

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/components/class-wc-retailcrm-logger.php
> +            if (empty(static::$startTime)) {
Не используй empty, startTime - флоат

2024-09-23 08:29 UTC, uryvskiy-dima commented on src/include/components/class-wc-retailcrm-logger.php
> +        public static function formatWCObject($object): array
Разбей на 2 метода formatWcOrder и formatWcCustomer

2024-09-26 16:02 UTC, Chupocabra commented on src/include/class-wc-retailcrm-base.php
> +            WC_Retailcrm_Logger::setEntry(__FUNCTION__);
Не придумал быстрого решения

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/api/class-wc-retailcrm-proxy.php
>                  /** @var \WC_Retailcrm_Response $response */
Это можно удалить /** @var \WC_Retailcrm_Response $response */

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/api/class-wc-retailcrm-proxy.php
Лишний отступ

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/api/class-wc-retailcrm-proxy.php
( ! class_exists( 'WC_Retailcrm_Client_V5' ) ) сделай  без лишних пробелов

(!class_exists( 'WC_Retailcrm_Client_V5' ))

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/api/class-wc-retailcrm-proxy.php
> +                count($arguments) === 0 ? '[no params]' : '[with params]',
А если тут будет не массив ? У тебя не указан тип для $arguments, если тут придет строка код упадет. Проверь просто на пустой массив $arguments === []

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/api/class-wc-retailcrm-proxy.php
> +        private function methodsWithoutFullLog()
Укажи возвращаемый тип массив, для getCorporateEnabled - bool и удали коммент для getCorporateEnabled,он не несет никакой полезной информации

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/class-wc-retailcrm-uploader.php
>              $ids = $_GET['order_ids_retailcrm'];
Отступ

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/components/class-wc-retailcrm-logger.php
> +        private static $currentHook;
Зачем эти комменты ? Укажи полям тип и удали эти комменты

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/order/class-wc-retailcrm-order-payment.php
> +                $logMessage = 'Payment for order: ' . $order->get_id() . '. ' .
Можно без переменной logMessage, иcпользуй sprintf

2024-09-27 07:51 UTC, uryvskiy-dima commented on tests/test-wc-retailcrm-base.php
> +        //Debug info
Можно удалить, не несет никакой информации

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/include/components/class-wc-retailcrm-logger.php
> +        public static function exception(string $method, Throwable $exception, string $additionalMessage = '')
По удаляй эти PHPDoc (комменты), по названию методов и так понятно что они делают, типы переменных ты указываешь в сигнатуре функций, где нужно добавь возвращаемый тип

2024-09-27 07:51 UTC, uryvskiy-dima commented on src/languages/retailcrm-ru_RU.l10n.php
> -        "Debug mode" => "Режим отладки",
Так же нужно удалить переводы с retailcrm-es_ES.pot и retailcrm-ru_RU.pot

2024-09-27 09:32 UTC, Chupocabra commented on src/include/components/class-wc-retailcrm-logger.php
> +        private static $currentHook;
Typed properties are only allowed since PHP 7.4

2024-09-27 09:42 UTC, Chupocabra commented on src/include/components/class-wc-retailcrm-logger.php
> +        public static function exception(string $method, Throwable $exception, string $additionalMessage = '')
Оставляю коммент для formatWcObject, думаю он полезен?

2024-09-27 10:06 UTC, uryvskiy-dima approved these changes

2024-09-30 06:29 UTC, merged